version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '10000:10000'
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    container_name: jenkins-app
